name: bot_noicecurse

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Your issue has been received! Thanks for spending your valuable time on this project :smile: We will respond soon :+1:'
        pr-message: 'Your PR has been received. It will be reviewed soon :smile:'
