name: Java CI
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: GitHub Actions for Apache Maven
      uses: actions/checkout@v1
    - run: |
        mvn clean install
        mvn test
        mvn site
        mvn deploy -Dregistry=https://maven.pkg.github.com/nishkarshraj -Dtoken=${{ secrets.GH_TOKEN }}
